rules:
  - config: p/kotlin                # Kotlin 언어 (Spring WebFlux 등)
  - config: p/java                  # Java 전반 품질 + 위험한 API 사용 등
  - config: owasp-java              # Java 기반 보안 취약점 (SQLi, XSS, SSRF 등)

  # 민감 정보/비밀번호/토큰 등 하드코딩 탐지
  - config: generic.secrets         # 모든 언어의 시크릿 키/패스워드 노출 감지

  # Dockerfile 보안 검사 (루트 사용자, 레이어 캐싱, 패키지 버전 등)
  - config: dockerfile              # Dockerfile 보안 룰셋

  # 배포 스크립트(Shell script) 보안 검사
  - config: p/bash                  # sh/bash script 보안 룰셋

  # Kubernetes YAML 구성 파일 (Deployment, Service 등)
  - config: r/kubernetes            # Kubernetes 리소스 설정 위험 감지 (RBAC, privileged 등)

  # YAML 파일 (Helm chart, 설정 등)
  - config: generic.security.yaml   # Helm chart 및 일반 YAML의 보안 검사

  # JSON 파일 (설정, secret, config 등)
  - config: generic.security.json   # JSON 내 시크릿 노출, 잘못된 설정 탐지
