# .github/workflows/semgrep.yml
name: Semgrep CI
on:
  push:
    branches: [ "main", "master" ] # 기본 브랜치 이름에 맞게 수정하세요.
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest

    permissions:
      security-events: write  # 보안 경고 업로드 권한
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep with SARIF output
        run: semgrep scan --config=auto --sarif --output=semgrep.sarif

      - name: Upload Semgrep SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

