# .github/workflows/semgrep.yml
name: Semgrep CI
on:
  push:
    branches: [ "main", "master" ] # 기본 브랜치 이름에 맞게 수정하세요.
  pull_request:
  workflow_dispatch:
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Semgrep 액션 실행 및 SARIF 파일 생성
      # Semgrep의 공식 규칙 세트(r/ci)를 사용하여 스캔하고 결과를 'semgrep.sarif' 파일로 저장
      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          # 스캔 결과를 SARIF 형식의 파일로 출력하도록 지정
          sarif_file: semgrep.sarif

      # 3. SARIF 파일을 GitHub Security 탭에 업로드
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # 업로드할 SARIF 파일의 경로 지정
          sarif_file: semgrep.sarif
        # 에러가 발생해도 워크플로우가 중단되지 않도록 설정 (선택 사항)
        if: always()

